# Generated by Django 3.1.1 on 2020-09-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200916_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
